import Head from 'next/head'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sitepoint Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, sitepoint blog, nextjs blog website, blog website, tech blog website" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.imagewrap}>
          <img className={styles.myImg} src='/home.jpg' width={284} height={284} alt='sitepoint blog image' />
        </div>
        
        <h1 className={styles.title}>
          <span className='dummy'>&lt;Sitepoint Blog/&gt;</span>
        </h1>

        <div>
          <h2 className={styles.h2}>Latest Blogs</h2>
          <div>
            <h3 className={styles.h3}>How to learn NextJs</h3>
            <p className={styles.p}>NextJs is an modified version of React which is used for both frontend and backend development.</p>
            <button className={styles.btn}>Read More</button>
          </div>

          <div>
            <h3 className={styles.h3}>How to learn JavaScript</h3>
            <p className={styles.p}>JavaScript is a programmin language which is used for both frontend and backend development.</p>
            <button className={styles.btn}>Read More</button>
          </div>

          <div>
            <h3 className={styles.h3}>How to learn Python</h3>
            <p className={styles.p}>Python is a programming language which is used for both frontend and backend development.</p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}