import Head from 'next/head'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2 {
            font-size: 38px;
          }

          h3 {
            font-size: 28px;
          }
        `}
      </style>
      <Head>
        <title>Sitepoint Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, sitepoint blog, nextjs blogg website" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className='dummy'>Sitepoint Blog</span>
        </h1>

        <div className={styles.imagewrap}>
          <img className={styles.myImg} src='/home.jpg' width={284} height={284} alt='sitepoint blog image' />
        </div>

        <p className={styles.description}>
          A Blog for coders written by a coder
        </p>

        <div>
          <h2>Latest Blogs</h2>
          <div className="blogItem">
            <h3>How to learn NextJs?</h3>
            <p>NextJs is an modified version of React which is used for both frontend and backend development</p>
          </div>

          <div className="blogItem">
            <h3>How to learn NextJs?</h3>
            <p>NextJs is an modified version of React which is used for both frontend and backend development</p>
          </div>

          <div className="blogItem">
            <h3>How to learn NextJs?</h3>
            <p>NextJs is an modified version of React which is used for both frontend and backend development</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}