import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
// import Script from 'next/script'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sitepoint Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, sitepoint blog, nextjs blogg website" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="/run.js"></script> */}
      </Head>

      {/* <Script src="/run.js" strategy='lazyOnload'></Script> */}

      <nav className={styles.main_navbar}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blogs</li>
          <li>Contact</li>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sitepoint Blog
        </h1>

        <p className={styles.description}>
          A Blog for coders written by a coder
        </p>

        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn NextJs in 2024?</h3>
            <p>NextJs is an modified version of React which is used for both frontend and backend development</p>
          </div>

          <div className="blogItem">
            <h3>How to learn NextJs in 2024?</h3>
            <p>NextJs is an modified version of React which is used for both frontend and backend development</p>
          </div>

          <div className="blogItem">
            <h3>How to learn NextJs in 2024?</h3>
            <p>NextJs is an modified version of React which is used for both frontend and backend development</p>
          </div>
        </div>


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
